#!/usr/bin/env bash

if [[ $0 != $BASH_SOURCE ]]; then
    echo "do not source this script"
    return 1
fi

SCRIPT_PATH=`(dirname $BASH_SOURCE)`
REPO_PATH=`(realpath $SCRIPT_PATH/..)`

while getopts ":dp" option; do
    case $option in
        d)
            export NIL_BUILD_CPACK_DEB=1
            export NIL_CPACK_OUT_DIR="$REPO_PATH/deb_pkg";;
        p)
            export NIL_UPLOAD_PYPI=1;;
        \?)
            echo "unknown option is provided: ${option}"
            exit 1;;
    esac
done

STATUS_FILE="vcpkg_installed/vcpkg/status"
if [[ -f "$STATUS_FILE" ]]; then
    tmp_status=$(mktemp)
    awk 'BEGIN { RS=""; ORS="\n\n" } $0 !~ /^Package: nil-/ { print }' \
        "$STATUS_FILE" > "$tmp_status"
    mv "$tmp_status" "$STATUS_FILE"
fi

rm -rf vcpkg_installed/x64-linux/debug/bin/nil*
rm -rf vcpkg_installed/x64-linux/debug/lib/libnil*
rm -rf vcpkg_installed/x64-linux/bin/nil-*
rm -rf vcpkg_installed/x64-linux/lib/libnil-*
rm -rf vcpkg_installed/x64-linux/include/nil-*
rm -rf vcpkg_installed/x64-linux/share/nil-*
rm -rf vcpkg_installed/x64-linux/share/doc/nil-*

${VCPKG_ROOT}/vcpkg                     \
    install                             \
    --overlay-ports=${REPO_PATH}/ports  \
    --binarysource=clear