#!/usr/bin/env bash

if [[ $0 != $BASH_SOURCE ]]; then
    echo "do not source this script"
    return 1
fi

SCRIPT_PATH=`(dirname $BASH_SOURCE)`
REPO_PATH=`(realpath $SCRIPT_PATH/..)`

PORT_COMMIT_MSG="${SCRIPT_PATH}/.commit.msg"
BASELINE_FILE="${REPO_PATH}/versions/baseline.json"
FORCE_UPDATE=0

parse_options() {
  while getopts ":f" option; do
      case $option in
          f)
              FORCE_UPDATE=1;;
          \?)
              echo "unknown option is provided: ${option}"
              exit 1;;
      esac
  done
}

update_port() {
  local port_name="$1"
  local port_version="$2"

  baseline_version="$(jq --arg name "$port_name" '.default[$name].baseline' $BASELINE_FILE)"
  if [[ $FORCE_UPDATE == 0 && "$port_version" == "${baseline_version:1:-1}" ]]; then
    return
  fi

  echo "updating port version: ${port_name} v${port_version}"

  port_homepage="$(jq -r '.homepage' "ports/$port_name/vcpkg.json")"
  port_hash="$(curl -LsS "${port_homepage}/archive/v${port_version}.tar.gz" | sha512sum | awk '{print $1}')"

  cat > "ports/${port_name}/portfile.cmake" <<EOF
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO "njaldea/\${PORT}"
    REF "v\${VERSION}"
    SHA512 ${port_hash}
    HEAD_REF master
)

include(\${CMAKE_CURRENT_LIST_DIR}/port.cmake)

if (DEFINED ENV{NIL_BUILD_CPACK_DEB} AND "\$ENV{NIL_BUILD_CPACK_DEB}" STREQUAL "1")
    set(BUILD_DIR "\${CURRENT_BUILDTREES_DIR}/\${TARGET_TRIPLET}-rel")
    message(STATUS "Running CPack in build directory \${BUILD_DIR}")

    execute_process(
        COMMAND cpack -G DEB -D CPACK_OUTPUT_FILE_PREFIX=\$ENV{NIL_CPACK_OUT_DIR}
        WORKING_DIRECTORY \${BUILD_DIR}
    )
endif()
EOF

  if [[ "$port_version" != "${baseline_version:1:-1}" ]]; then
    echo "[${port_name}]: v${port_version}" >> "${PORT_COMMIT_MSG}"
  fi
}

update_baseline_file() {
  local port_name="$1"
  local port_version="$2"

  jq                                                                           \
    --arg name "$port_name"                                                    \
    --arg ver "$port_version"                                                  \
    --argjson pv 0                                                             \
    '.default[$name].baseline = $ver | .default[$name]["port-version"] = $pv'  \
    "$BASELINE_FILE" > ${SCRIPT_PATH}/.tmp.json &&                             \
    mv ${SCRIPT_PATH}/.tmp.json "$BASELINE_FILE"
}

update_baseline() {
  local port_name="$1"
  local port_version="$2"

  port_rev_parse="$(git -C $REPO_PATH rev-parse HEAD:ports/$port_name)"
  version_file="${REPO_PATH}/versions/n-/${port_name}.json"

  index=$(jq -r --arg ver "$port_version"                                           \
    '.versions | to_entries | map(select(.value.version == $ver)) | .[0].key // -1' \
    "$version_file")

  if [[ $index != -1 ]]; then
    if [[ $FORCE_UPDATE == 1 ]]; then
      echo "${port_name}: updating version"
      jq                                                                      \
        --argjson index $index                                                \
        --arg ver "$port_version"                                             \
        --arg tree "$port_rev_parse"                                          \
        '.versions[$index] = {"version": $ver, "git-tree": $tree}'            \
        "$version_file" > .tmp.json && mv .tmp.json "$version_file"
      update_baseline_file "$port_name" "$port_version"
    fi
  else
    echo "${port_name}: appending version"

    jq                                                                          \
      --arg ver "$port_version"                                                 \
      --arg tree "$port_rev_parse"                                              \
       '.versions += [{"version": $ver, "git-tree": $tree}]'                    \
       "$version_file" > .tmp.json && mv .tmp.json "$version_file"
    update_baseline_file "$port_name" "$port_version"
  fi
}

update_ports() {
  read -r -p "Do you want to update ports? [y/N] " PORT_UPDATE
  PORT_UPDATE=${PORT_UPDATE,,}

  if [[ $PORT_UPDATE == "y" ]]; then
    echo -n "" > "${PORT_COMMIT_MSG}"
    for dir in ${REPO_PATH}/ports/nil-*; do
      port_name="$(basename "$dir")"
      port_version="$(jq -r '.version' "$dir/vcpkg.json")"

      update_port $port_name $port_version
    done
  fi
}

commit_ports() {
  if [ -n "$(git status --porcelain)" ]; then
    echo "Working directory has changes"
    read -r -p "Do you want to commit port changes? [y/N] " PORT_COMMIT
    PORT_COMMIT=${PORT_COMMIT,,}

    if [[ $PORT_COMMIT == "y" ]]; then
      git add .
      git commit -F "${PORT_COMMIT_MSG}"
    fi
  fi
}

update_baselines() {
  read -r -p "Do you want to update baselines? [y/N] " BASELINE_UPDATE
  BASELINE_UPDATE=${BASELINE_UPDATE,,}

  if [[ $BASELINE_UPDATE == "y" ]]; then
    for dir in ${REPO_PATH}/ports/nil-*; do
      port_name="$(basename "$dir")"
      port_version="$(jq -r '.version' "$dir/vcpkg.json")"

      update_baseline $port_name $port_version
    done
  fi
}

commit_baselines() {
  if [ -n "$(git status --porcelain)" ]; then
    echo "Working directory has changes"
    read -r -p "Do you want to commit baseline changes? [y/N] " BASELINE_COMMIT
    BASELINE_COMMIT=${BASELINE_COMMIT,,}

    if [[ $BASELINE_COMMIT == "y" ]]; then
      git add .
      git commit -m "update versions"
    fi
  fi
}

main() {
  parse_options $@
  update_ports
  commit_ports
  update_baselines
  commit_baselines
}

main $@