#!/usr/bin/env bash

if [[ $0 != $BASH_SOURCE ]]; then
    echo "do not source this script"
    return 1
fi

SCRIPT_PATH=`(dirname $BASH_SOURCE)`
REPO_PATH=`(realpath $SCRIPT_PATH/..)`

BASELINE_FILE="${REPO_PATH}/versions/baseline.json"
FORCE_UPDATE=0

while getopts ":f" option; do
    case $option in
        f)
            FORCE_UPDATE=1;;
        \?)
            echo "unknown option is provided: ${option}"
            exit 1;;
    esac
done

update_baseline() {
  local port_name="$1"
  local port_version="$2"

  jq                                                                           \
    --arg name "$port_name"                                                    \
    --arg ver "$port_version"                                                  \
    --argjson pv 0                                                             \
    '.default[$name].baseline = $ver | .default[$name]["port-version"] = $pv'  \
    "$BASELINE_FILE" > .tmp.json && mv .tmp.json "$BASELINE_FILE"
}

for dir in ${REPO_PATH}/ports/*; do
  port_name="$(basename "$dir")"
  port_version="$(jq -r '.version' "$dir/vcpkg.json")"
  port_rev_parse="$(git -C $REPO_PATH rev-parse HEAD:ports/$port_name)"
  
  version_file="${REPO_PATH}/versions/n-/${port_name}.json"

  index=$(jq -r --arg ver "$port_version"                                           \
    '.versions | to_entries | map(select(.value.version == $ver)) | .[0].key // -1' \
    "$version_file")

  if [[ $index != -1 ]]; then
    if [[ $FORCE_UPDATE == 1 ]]; then
      echo "${port_name}: updating"
      jq                                                                      \
        --argjson index $index                                                \
        --arg ver "$port_version"                                             \
        --arg tree "$port_rev_parse"                                          \
        '.versions[$index] = {"version": $ver, "git-tree": $tree}'            \
        "$version_file" > .tmp.json && mv .tmp.json "$version_file"
      update_baseline "$port_name" "$port_version"
    fi
  else
    echo "${port_name}: appending"

    jq                                                                          \
      --arg ver "$port_version"                                                 \
      --arg tree "$port_rev_parse"                                              \
       '.versions += [{"version": $ver, "git-tree": $tree}]'                    \
       "$version_file" > .tmp.json && mv .tmp.json "$version_file"
    update_baseline "$port_name" "$port_version"
  fi
done
